### ISSUE TITLE
版本较低，能不能升级为031的

### ISSUE THREAD

**Issue by zaixia** [doc-ark-online/learning-docs#180]
### 所属页面地址

https://learning.ark.online/obby-course/game-description.html

### 选中内容

https://arkimg.ark.online/闯关小游戏027.rar

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by onionkingdom** [comment]
😁 已经更新

**Comment by zaixia** [comment]
我进入教程-闯关小游戏进入依然是显示：https://arkimg.ark.online/闯关小游戏027.rar


陈思达
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doc-ark-online/learning-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月4日(星期四) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doc-ark-online/learning-docs] 版本较低，能不能升级为031的 (Issue #180)





 
😁 已经更新
